<a href="https://colab.research.google.com/github/twadhwa/ML_Templates/blob/main/Logistic_Regression/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 


In [2]:
data = pd.read_csv("/content/drive/MyDrive/Machine Learning Data Sets /Classification Data /Social_Network_Ads.csv")

In [3]:
data 


Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [5]:
X = data.iloc[:,:-1].values 
y = data.iloc[:,-1].values 

In [10]:
from sklearn.model_selection import train_test_split 
X_train, X_test ,y_train ,y_test  = train_test_split(X,y,test_size = 0.2)


In [11]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()


In [13]:
model.fit(X_train,y_train )

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
y_pred = model.predict(X_test)

In [15]:
y_test

array([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1])

In [16]:
y_pred 

array([0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1])

In [21]:
from sklearn.metrics import accuracy_score , confusion_matrix 
print("The Accuracy score of the model is :" , accuracy_score(y_test , y_pred))
print("The confusion matrix of the model is : \n" , confusion_matrix(y_test,y_pred))

The Accuracy score of the model is : 0.8875
The confusion matrix of the model is : 
 [[49  4]
 [ 5 22]]
